// automatically generated by the FlatBuffers compiler, do not modify

package us.dustinj.timezonemap.serialization.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DeltaPoint extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DeltaPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int latitude() { return bb.getInt(bb_pos + 0); }
  public int longitude() { return bb.getInt(bb_pos + 4); }

  public static int createDeltaPoint(FlatBufferBuilder builder, int latitude, int longitude) {
    builder.prep(4, 8);
    builder.putInt(longitude);
    builder.putInt(latitude);
    return builder.offset();
  }
}

