// automatically generated by the FlatBuffers compiler, do not modify

package us.dustinj.timezonemap.serialization.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Polygon extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Polygon getRootAsPolygon(ByteBuffer _bb) { return getRootAsPolygon(_bb, new Polygon()); }
  public static Polygon getRootAsPolygon(ByteBuffer _bb, Polygon obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Polygon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public us.dustinj.timezonemap.serialization.flatbuffer.Ring rings(int j) { return rings(new us.dustinj.timezonemap.serialization.flatbuffer.Ring(), j); }
  public us.dustinj.timezonemap.serialization.flatbuffer.Ring rings(us.dustinj.timezonemap.serialization.flatbuffer.Ring obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int ringsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public us.dustinj.timezonemap.serialization.flatbuffer.Ring.Vector ringsVector() { return ringsVector(new us.dustinj.timezonemap.serialization.flatbuffer.Ring.Vector()); }
  public us.dustinj.timezonemap.serialization.flatbuffer.Ring.Vector ringsVector(us.dustinj.timezonemap.serialization.flatbuffer.Ring.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPolygon(FlatBufferBuilder builder,
      int ringsOffset) {
    builder.startTable(1);
    Polygon.addRings(builder, ringsOffset);
    return Polygon.endPolygon(builder);
  }

  public static void startPolygon(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRings(FlatBufferBuilder builder, int ringsOffset) { builder.addOffset(0, ringsOffset, 0); }
  public static int createRingsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRingsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPolygon(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Polygon get(int j) { return get(new Polygon(), j); }
    public Polygon get(Polygon obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

