// automatically generated by the FlatBuffers compiler, do not modify

package us.dustinj.timezonemap.serialization.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Ring extends Table {
  public static Ring getRootAsRing(ByteBuffer _bb) { return getRootAsRing(_bb, new Ring()); }
  public static Ring getRootAsRing(ByteBuffer _bb, Ring obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Ring __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Point points(int j) { return points(new Point(), j); }
  public Point points(Point obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 8, bb) : null; }
  public int pointsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createRing(FlatBufferBuilder builder,
      int pointsOffset) {
    builder.startObject(1);
    Ring.addPoints(builder, pointsOffset);
    return Ring.endRing(builder);
  }

  public static void startRing(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPoints(FlatBufferBuilder builder, int pointsOffset) { builder.addOffset(0, pointsOffset, 0); }
  public static void startPointsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static int endRing(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

